version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
      - "./mods:/mods"
    environment:
      SERVER_NAME: "Ourcraft"
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.1"
      MEMORY: "8G"
      MOTD: "Welcome to ourcraft server!"
      OVERRIDE_ICON: "TRUE"
      ICON: "https://cdna.artstation.com/p/assets/images/images/037/831/198/large/mark-galbraith-minecraftbee.jpg"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      SEED: "3730784288373098496"
      VIEW_DISTANCE: "16"
      DIFFICULTY: "normal"
      MODE: "survival"
      FORCE_GAMEMODE: "TRUE"
      MAX_PLAYERS: "15"
      PLAYER_IDLE_TIMEOUT: "30"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      WHITELIST: "frannyg_,LeynaM,Jack_Pear,TiaWM"
      ENFORCE_WHITELIST: "TRUE"
      OPS: "frannyg_"
      SPAWN_PROTECTION: "0"
      RESOURCE_PACK: "https://drive.google.com/uc?export=download&id=1Tbr7mY2iE6yWnkkdzfl5BXYmdJgdB-e6" # Resource Pack: https://vanillatweaks.net/share#3wo9Wq
      RESOURCE_PACK_ENFORCE: "TRUE"
      VANILLATWEAKS_SHARECODE: "SDS4bp,jv7TBK" # Datapacks: https://vanillatweaks.net/share#SDS4bp, Crafting Tweaks: https://vanillatweaks.net/share#jv7TBK
      MODS_FILE: "/mods/mods.txt"
      REMOVE_OLD_MODS: "TRUE"
      REMOVE_OLD_DATAPACKS: "TRUE"
      ENABLE_RCON: "TRUE"
      RCON_PORT: "25575"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      MAX_TICK_TIME: "-1"
      STOP_SERVER_ANNOUNCE_DELAY: "120"
    restart: always
