version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
      - "./plugins:/plugins"
      - "./datapacks:/datapacks"
      - "./config/chest_cleaner_config.yml:/data/plugins/ChestCleaner/config.yml"
    environment:
      SERVER_NAME: "Ourcraft"
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "8G"
      MOTD: "Welcome to ourcraft server!"
      OVERRIDE_ICON: "TRUE"
      ICON: "https://cdna.artstation.com/p/assets/images/images/037/831/198/large/mark-galbraith-minecraftbee.jpg"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      DIFFICULTY: "normal"
      MODE: "survival"
      FORCE_GAMEMODE: "TRUE"
      MAX_PLAYERS: "15"
      PLAYER_IDLE_TIMEOUT: "30"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      WHITELIST: "frannyg_,LeynaM"
      ENFORCE_WHITELIST: "TRUE"
      OPS: "frannyg_"
      SPAWN_PROTECTION: "0"
      REPLACE_ENV_VARIABLES: "TRUE"
      REPLACE_ENV_IN_PLACE: "TRUE"
      REPLACE_ENV_DURING_SYNC: "TRUE"
      ENV_VARIABLE_PREFIX: "DISCORD_"
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      DISCORD_GUILD: "${DISCORD_GUILD}"
      DISCORD_URL: "${DISCORD_URL}"
      DISCORD_PRIMARY: "${DISCORD_PRIMARY}"
      DISCORD_CONSOLE_CHANNEL: "${DISCORD_CONSOLE_CHANNEL}"
      RESOURCE_PACK: "https://drive.google.com/uc?export=download&id=1RX449QtQBKLjoCLl3dw0puUF98hIOQzl"
      RESOURCE_PACK_ENFORCE: "TRUE"
      REMOVE_OLD_MODS: "TRUE"
      REMOVE_OLD_DATAPACKS: "TRUE"
      DATAPACKS: "/datapacks/terralith-v2.0.9.zip,
        /datapacks/vanilla_tweaks_crafting.zip,
        /datapacks/afk_display-v1.1.2.zip,
        /datapacks/cauldron_concrete-v2.0.5.zip,
        /datapacks/chunk_loaders-v1.0.3.zip,
        /datapacks/coordinates_hud-v1.2.2.zip,
        /datapacks/custom_nether_portals-v2.3.4.zip,
        /datapacks/larger_phantoms-v1.2.3.zip,
        /datapacks/more_mob_heads-v2.9.4.zip,
        /datapacks/player_head_drops-v1.1.2.zip,
        /datapacks/villager_death_messages-v1.2.3.zip"
      ENABLE_RCON: "TRUE"
      RCON_PORT: "25575"
      RCON_PASSWORD: "${RCON_PASSWORD}"
      MAX_TICK_TIME: "-1"
      ENABLE_AUTOPAUSE: "TRUE"
      AUTOPAUSE_TIMEOUT_EST: "900"
      AUTOPAUSE_TIMEOUT_INIT: "300"
    restart: always
